-- Vérifier la structure de la table LigneCommande
SELECT
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'LigneCommande'
ORDER BY ORDINAL_POSITION;
