-- Check schema of empty tables
USE STA_SAV_DB;
GO

PRINT 'Schema des tables vides:';
PRINT '';

-- InterventionCatalog
PRINT '1. InterventionCatalog:';
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'InterventionCatalog'
ORDER BY ORDINAL_POSITION;
PRINT '';

-- PromotionVehicule
PRINT '2. PromotionVehicule:';
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PromotionVehicule'
ORDER BY ORDINAL_POSITION;
PRINT '';

-- MessageAccueil
PRINT '3. MessageAccueil:';
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'MessageAccueil'
ORDER BY ORDINAL_POSITION;
PRINT '';

-- Feedback
PRINT '4. Feedback:';
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Feedback'
ORDER BY ORDINAL_POSITION;
PRINT '';

-- HistoriqueRDV
PRINT '5. HistoriqueRDV:';
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'HistoriqueRDV'
ORDER BY ORDINAL_POSITION;
PRINT '';

-- MessageLecture
PRINT '6. MessageLecture:';
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'MessageLecture'
ORDER BY ORDINAL_POSITION;
PRINT '';

-- AuditLog
PRINT '7. AuditLog:';
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'AuditLog'
ORDER BY ORDINAL_POSITION;
PRINT '';

GO
