global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'sta-chery-api'
    static_configs:
      - targets: ['backend:3000']

  - job_name: 'redis'
    static_configs:
      - targets: ['projet_PFE_redis_exporter:9121']

  - job_name: 'postgresql'
    static_configs:
      - targets: ['projet_PFE_postgres_exporter:9187']
