'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'fr' | 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de bord',
    'nav.catalog': 'Catalogue',
    'nav.appointments': 'Rendez-vous',
    'nav.vehicles': 'Véhicules',
    'nav.orders': 'Commandes',
    'nav.complaints': 'Réclamations',
    'nav.documents': 'Documents',
    'nav.assistance': 'Assistance',
    'nav.feedback': 'Avis',
    'nav.profile': 'Profil',
    'nav.logout': 'Déconnexion',
    'nav.clientDashboard': 'Tableau de bord',
    'nav.clientVehicles': 'Mes véhicules',
    'nav.clientHistory': 'Historique véhicules',
    'nav.clientRepairOrders': 'Commandes de réparation',
    'nav.clientCatalog': 'Catalogue',
    'nav.clientPromotions': 'Promotions',
    'nav.clientAppointments': 'Rendez-vous',
    'nav.clientOrders': 'Mes commandes',
    'nav.clientDocuments': 'Mes documents',
    'nav.clientInformations': 'Informations',
    'nav.clientChatbot': 'Assistant SAV',
    'nav.clientAssistance': 'Assistance',
    'nav.clientFeedback': 'Mes Avis',
    'nav.clientComplaints': 'Réclamations',
    'nav.clientProfile': 'Mon profil',
    'nav.clientSpace': 'Espace Client',
    'PRINCIPAL': 'PRINCIPAL',
    'SUIVI': 'SUIVI',
    'AUTRES': 'AUTRES',

    // Common
    'common.welcome': 'Bienvenue',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.add': 'Ajouter',
    'common.close': 'Fermer',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.confirm': 'Confirmer',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.submit': 'Soumettre',
    'common.view': 'Voir',
    'common.download': 'Télécharger',
    'common.upload': 'Téléverser',
    'common.select': 'Sélectionner',
    'common.all': 'Tous',
    'common.none': 'Aucun',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.details': 'Détails',
    'common.unknown': 'Non défini',
    'common.total': 'Total',
    'common.inProgress': 'En cours',
    'common.completed': 'Terminées',
    'common.totalCost': 'Coût total',
    'common.orders': 'Mes Commandes',
    'common.quickAccess': 'Accès rapide',
    'common.myVehicles': 'Mes Véhicules',
    'common.editProfile': 'Modifier le profil',
    'common.client': 'CLIENT',
    'common.email': 'Email',
    'common.phone': 'Téléphone',
    'common.clientId': 'ID Client',
    'common.addFirstVehicle': 'Ajouter mon premier véhicule',
    'common.noVehicle': 'Aucun véhicule enregistré',
    'common.chassisNumber': 'N° Châssis',
    'common.vehiclesCount': 'Véhicules',
    'common.nextAppointments': 'RDV à venir',
    'common.send': 'Envoyer',
    'common.writeMessage': 'Écrivez votre message...',
    'common.available247': 'Disponible 24h/24',

    // Auth
    'auth.login': 'Connexion',
    'auth.register': 'Inscription',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.forgotPassword': 'Mot de passe oublié?',
    'auth.rememberMe': 'Se souvenir de moi',

    // Dashboard
    'dashboard.title': 'Tableau de bord',
    'dashboard.stats': 'Statistiques',
    'dashboard.recentActivity': 'Activité récente',
    'dashboard.welcomeBack': 'Bienvenue de retour',
    'dashboard.manageAppointments': 'Gérez vos rendez-vous atelier',
    'dashboard.managePersonalInfo': 'Gérez vos informations personnelles',
    'dashboard.see': 'Voir',
    'dashboard.edit': 'Éditer',
    'dashboard.add': 'Ajouter',
    'dashboard.hello': 'Bonjour',
    'dashboard.welcomeMessage': 'Bienvenue sur votre espace client STA Chery Tunisia',
    'dashboard.takeAppointment': 'Prendre un RDV',
    'dashboard.myVehicles': 'Mes véhicules',
    'dashboard.upcomingAppointments': 'RDV à venir',
    'dashboard.vehicles': 'Véhicules',
    'dashboard.complaints': 'Réclamations',
    'dashboard.completedAppointments': 'RDV complétés',
    'dashboard.thisMonth': 'ce mois',
    'dashboard.myAppointments': 'Mes Rendez-vous',
    'dashboard.viewAll': 'Voir tout',
    'dashboard.noUpcomingAppointments': 'Aucun rendez-vous à venir',
    'dashboard.quickActions': 'Actions rapides',
    'dashboard.bookAppointment': 'Réserver un nouveau rendez-vous',
    'dashboard.submitComplaint': 'Soumettre réclamation',
    'dashboard.reportProblem': 'Signaler un problème',
    'dashboard.noVehicles': 'Aucun véhicule enregistré',
    'dashboard.addVehicle': 'Ajouter un véhicule',
    'dashboard.serviceAppointment': 'Rendez-vous de service',
    'dashboard.vehicle': 'Véhicule',
    'dashboard.agency': 'Agence',
    'dashboard.confirmed': 'Confirmé',
    'dashboard.planned': 'Planifié',
    'dashboard.inProgress': 'En cours',
    'dashboard.validated': 'Validé',
    'dashboard.pending': 'En attente',
    'dashboard.refused': 'Refusé',
    'dashboard.undefined': 'Non défini',
    'dashboard.unknownPlate': 'Immatriculation inconnue',

    // Catalog
    'catalog.title': 'Catalogue de Services',
    'catalog.discoverServices': 'Découvrez nos services et packages d\'entretien',
    'catalog.search': 'Rechercher...',
    'catalog.serviceTypes': 'Types de service',
    'catalog.servicesAvailable': 'Services disponibles',
    'catalog.packagesAvailable': 'Packages disponibles',
    'catalog.averageDuration': 'Durée moyenne',
    'catalog.packages': 'Packages',
    'catalog.allServices': 'Tous les services',
    'catalog.maintenancePackages': 'Packages d\'entretien',
    'catalog.saveWithBundles': 'Économisez avec nos offres groupées',
    'catalog.noPackagesFound': 'Aucun package trouvé',
    'catalog.interventionsIncluded': 'intervention(s) incluse(s)',
    'catalog.viewDetails': 'Voir détails',
    'catalog.noTypesFound': 'Aucun type trouvé',
    'catalog.delay': 'Délai',
    'catalog.services': 'service(s)',
    'catalog.noServicesFound': 'Aucun service trouvé',
    'catalog.packageDetails': 'Détails du Package',
    'catalog.servicesIncluded': 'Services inclus',
    'catalog.toBookPackage': 'Pour réserver ce package, rendez-vous dans la section "Rendez-vous" et sélectionnez les services inclus.',
    'catalog.interventions': 'Interventions',
    'catalog.price': 'Prix',
    'catalog.duration': 'Durée',
    'catalog.details': 'Détails',
    'catalog.bookNow': 'Réserver maintenant',

    // Appointments
    'appointments.title': 'Mes rendez-vous',
    'appointments.total': 'au total',
    'appointments.manageAppointments': 'Gérez vos rendez-vous et suivez leur statut',
    'appointments.bookAppointment': 'Réserver un rendez-vous',
    'appointments.vehicleValidationRequired': 'Vous devez attendre la validation de votre véhicule par un agent SAV avant de réserver un rendez-vous.',
    'appointments.dayWithAppointment': 'Jour avec rendez-vous',
    'appointments.today': 'Aujourd\'hui',
    'appointments.allAppointments': 'Tous les rendez-vous',
    'appointments.all': 'Tous',
    'appointments.planned': 'Planifiés',
    'appointments.inProgress': 'En cours',
    'appointments.completed': 'Terminés',
    'appointments.noAppointmentsFound': 'Aucun rendez-vous trouvé',
    'appointments.bookNow': 'Réserver maintenant',
    'appointments.step': 'Étape',
    'appointments.of': 'sur',
    'appointments.selectVehicleAndService': 'Sélectionner le véhicule et le service',
    'appointments.agency': 'Agence',
    'appointments.selectAgency': 'Sélectionner une agence',
    'appointments.vehicle': 'Véhicule',
    'appointments.selectVehicle': 'Sélectionner un véhicule',
    'appointments.serviceType': 'Type de service',
    'appointments.selectServiceType': 'Sélectionner un type de service',
    'appointments.packagesAvailable': 'Packages disponibles',
    'appointments.packagesSelected': 'sélectionné(s)',
    'appointments.estimatedTotalPrice': 'Prix total estimatif',
    'appointments.packagesSelectedCount': 'package(s) sélectionné(s)',
    'appointments.selectDateAndTime': 'Sélectionner la date et l\'heure',
    'appointments.date': 'Date',
    'appointments.timeSlot': 'Créneau horaire',
    'appointments.slotFull': 'Créneau complet',
    'appointments.reservations': 'réservations',
    'appointments.placesRemaining': 'place(s) restante(s) sur',
    'appointments.full': 'Complet',
    'appointments.available': 'disponible',
    'appointments.selectAvailableSlot': 'Sélectionnez un créneau disponible',
    'appointments.noSlotsAvailable': 'Aucun créneau disponible pour cette date',
    'appointments.noSlotsForDate': 'Aucun créneau disponible pour cette date. Veuillez sélectionner une autre date.',
    'appointments.additionalNotes': 'Notes additionnelles',
    'appointments.specialRequest': 'Demande spéciale ou informations complémentaires...',
    'appointments.characters': 'caractères',
    'appointments.verifyAndConfirm': 'Vérifier et confirmer',
    'appointments.within24h': 'Attention : Vous réservez un rendez-vous dans moins de 24h. Veuillez vous assurer de votre disponibilité.',
    'appointments.service': 'Service',
    'appointments.selectedPackages': 'Packages sélectionnés',
    'appointments.estimatedPrice': 'Prix estimatif',
    'appointments.time': 'Heure',
    'appointments.remarks': 'Remarques',
    'appointments.back': 'Retour',
    'appointments.next': 'Suivant',
    'appointments.processing': 'Traitement...',
    'appointments.confirmAppointment': 'Confirmer le rendez-vous',
    'appointments.detailsTitle': 'Détails du rendez-vous',
    'appointments.dateAndTime': 'Date et heure',
    'appointments.services': 'Services',
    'appointments.servicesCount': 'service(s)',
    'appointments.serviceDetails': 'Détails des services',
    'appointments.noServiceSpecified': 'Aucun service spécifié',
    'appointments.notes': 'Notes',
    'appointments.cancelAppointment': 'Annuler le rendez-vous',
    'appointments.cancelReason': 'Raison de l\'annulation (optionnel)',
    'appointments.close': 'Fermer',
    'appointments.cancelling': 'Annulation...',
    'appointments.cancelButton': 'Annuler le rendez-vous',
    'appointments.errorSelectAll': 'Veuillez sélectionner tous les champs obligatoires',
    'appointments.errorSelectDateTime': 'Veuillez sélectionner une date et une heure',
    'appointments.new': 'Nouveau rendez-vous',
    'appointments.status': 'Statut',
    'appointments.cancel': 'Annuler',

    // Vehicles
    'vehicles.title': 'Mes véhicules',
    'vehicles.add': 'Ajouter un véhicule',
    'vehicles.addVehicle': 'Ajouter un véhicule',
    'vehicles.addNewVehicle': 'Ajouter un nouveau véhicule',
    'vehicles.brand': 'Marque',
    'vehicles.model': 'Modèle',
    'vehicles.year': 'Année',
    'vehicles.vin': 'Numéro de châssis',
    'vehicles.plate': 'Immatriculation',
    'vehicles.registration': 'Immatriculation',
    'vehicles.color': 'Couleur',
    'vehicles.mileage': 'Kilométrage',
    'vehicles.validated': 'Validé',
    'vehicles.registeredVehicles': 'véhicule(s) enregistré(s)',
    'vehicles.confirmDelete': 'Êtes-vous sûr de vouloir supprimer ce véhicule ?',
    'vehicles.deleteSuccess': 'Véhicule supprimé avec succès',
    'vehicles.deleteError': 'Erreur lors de la suppression du véhicule',
    'vehicles.modify': 'Modifier',
    'vehicles.delete': 'Supprimer',
    'vehicles.vehicle': 'Véhicule',
    'vehicles.detailsUnavailable': 'Détails non disponibles',
    'vehicles.selectBrand': 'Sélectionnez une marque',
    'vehicles.selectModel': 'Sélectionnez un modèle',
    'vehicles.selectVersion': 'Sélectionnez une version',
    'vehicles.selectColor': 'Sélectionnez une couleur',
    'vehicles.version': 'Version',
    'vehicles.chassisNumber': 'Numéro de châssis',
    'vehicles.plateType': 'Type d\'immatriculation',
    'vehicles.tunisFormat': 'Format Tunis',
    'vehicles.ntFormat': 'Format N.T',
    'vehicles.maxPlateNumber': 'Le numéro ne peut pas dépasser 260',
    'vehicles.preview': 'Aperçu',
    'vehicles.loading': 'Chargement...',
    'vehicles.photos': 'Photos',
    'vehicles.vehiclePhoto': 'Photo du véhicule',
    'vehicles.carteGrisePhoto': 'Photo de la carte grise',
    'vehicles.imageFormat': 'Format accepté : JPG, PNG (max 5MB)',
    'vehicles.removeImage': 'Supprimer l\'image',
    'vehicles.vehicleAdded': 'Véhicule ajouté avec succès',
    'vehicles.vehicleAddedSuccess': 'Votre véhicule a été enregistré avec succès. Il sera visible dans votre liste après validation par un agent SAV.',
    'vehicles.viewMyVehicles': 'Voir mes véhicules',
    'vehicles.vehicleInfo': 'Informations du véhicule',
    'vehicles.fillRequired': 'Remplissez les champs obligatoires',
    'vehicles.validationNotice': 'Note : Après l\'ajout de votre véhicule, vous devrez attendre la validation d\'un agent SAV avant qu\'il n\'apparaisse dans votre liste.',
    'vehicles.optional': '(Optionnel)',

    // Orders
    'orders.noOrders': 'Aucune commande de réparation',
    'orders.bookAppointment': 'Réserver un rendez-vous',
    'orders.order': 'Commande',
    'orders.agency': 'Agence',
    'orders.interventions': 'Interventions',
    'orders.cost': 'Coût',
    'orders.appointmentDate': 'Date du rendez-vous',
    'orders.estimatedDuration': 'Durée estimée',
    'orders.vehicle': 'Véhicule',
    'orders.brandModel': 'Marque/Modèle',
    'orders.plate': 'Immatriculation',
    'orders.color': 'Couleur',
    'orders.year': 'Année',
    'orders.agentAssigned': 'Agent assigné',
    'orders.attachments': 'Pièces jointes',
    'orders.download': 'Télécharger',
    'orders.undefined': 'Non défini',
    'orders.loadingError': 'Erreur lors du chargement des commandes',
    'orders.detailsError': 'Erreur lors du chargement des détails',
    'orders.detailsTitle': 'Détails de la commande',

    // Chatbot
    'chatbot.title': 'Assistant SAV Chery',
    'chatbot.greeting': '👋 Bonjour ! Je suis l\'assistant SAV Chery Tunisie. Comment puis-je vous aider ?',
    'chatbot.typing': 'Assistant en train de répondre...',
    'chatbot.fallback': '⚠️ Service temporairement indisponible. Appelez-nous au +216 XX XXX XXX',

    // Assistance
    'assistance.title': 'Assistance Diagnostic',
    'assistance.subtitle': 'Décrivez votre problème et trouvez des solutions',
    'assistance.findHelp': 'Trouvez l\'aide dont vous avez besoin',
    'assistance.searchInAssistance': 'Rechercher dans l\'assistance...',
    'assistance.search': 'Rechercher',
    'assistance.frequentQuestions': 'Questions fréquentes',
    'assistance.findAnswers': 'Trouvez des réponses aux questions courantes',
    'assistance.contactSupport': 'Contacter le support',
    'assistance.talkDirectly': 'Parlez directement avec notre équipe',
    'assistance.userGuide': 'Guide d\'utilisation',
    'assistance.learnToUse': 'Apprenez à utiliser la plateforme',
    'assistance.liveChat': 'Chat en direct',
    'assistance.instantAssistance': 'Assistance instantanée',
    'assistance.access': 'Accéder',
    'assistance.enterProblem': 'Veuillez entrer une description du problème',
    'assistance.searchPlaceholder': 'Ex: Bruit au démarrage, voyant moteur allumé...',
    'assistance.searching': 'Recherche...',
    'assistance.viewSolution': 'Voir la solution',
    'assistance.problemDescription': 'Description du problème',
    'assistance.recommendedSolution': 'Solution recommandée',
    'assistance.problemPersists': '💡 Si le problème persiste, nous vous recommandons de prendre rendez-vous avec un de nos techniciens.',
    'assistance.commonProblems': 'Problèmes fréquents',
    'assistance.suggestion.engineLight': 'Voyant moteur allumé',
    'assistance.suggestion.brakeNoise': 'Bruit au freinage',
    'assistance.suggestion.startIssue': 'Problème de démarrage',
    'assistance.suggestion.acIssue': 'Climatisation inefficace',
    'assistance.suggestion.steeringVibration': 'Vibrations au volant',
    'assistance.suggestion.highConsumption': 'Consommation excessive',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.markAllRead': 'Tout marquer comme lu',
    'notifications.empty': 'Aucune notification',
    'notifications.loading': 'Chargement...',
    'notifications.justNow': 'À l\'instant',
    'notifications.minutesAgo': 'Il y a {count} min',
    'notifications.hoursAgo': 'Il y a {count}h',
    'notifications.yesterday': 'Hier',
    'notifications.daysAgo': 'Il y a {count}j',
    'notifications.markedReadSuccess': 'Toutes les notifications marquées comme lues',

    // Language
    'language.french': 'Français',
    'language.arabic': 'العربية',
    'language.english': 'English',
    'language.select': 'Choisir la langue',
    'language.frShort': 'FR',
    'language.arShort': 'AR',
    'language.enShort': 'EN',

    // Profile Page
    'profile.title': 'Profil',
    'profile.modifyInfo': 'Modifier les informations',
    'profile.updatePersonalInfo': 'Mettez à jour vos informations personnelles',
    'profile.accountSecurity': 'Sécurité du compte',
    'profile.changePasswordRegularly': 'Modifiez votre mot de passe régulièrement',
    'profile.currentPassword': 'Mot de passe actuel',
    'profile.newPassword': 'Nouveau mot de passe',
    'profile.confirmNewPassword': 'Confirmer le nouveau mot de passe',
    'profile.changePassword': 'Modifier le mot de passe',
    'profile.saveChanges': 'Enregistrer les modifications',
    'profile.firstName': 'Prénom',
    'profile.lastName': 'Nom',
    'profile.passwordStrength': 'Force du mot de passe',
    'profile.weak': 'Faible',
    'profile.medium': 'Moyen',
    'profile.strong': 'Fort',
    'profile.saving': 'Enregistrement...',
    'profile.modifying': 'Modification...',
    'profile.notModifiable': 'Non modifiable',
    'profile.administrator': 'Administrateur',
    'profile.agent': 'Agent SAV',
    'profile.direction': 'Direction',
    'profile.client': 'Client',

    // Feedback Page
    'feedback.title': 'Vos Avis',
    'feedback.shareExperience': 'Partagez votre expérience avec nos services',
    'feedback.noCompletedAppointments': 'Aucun rendez-vous terminé',
    'feedback.leaveReviewAfterService': 'Vous pourrez laisser un avis après votre premier service',
    'feedback.appointment': 'Rendez-vous',
    'feedback.reviewGiven': 'Avis donné',
    'feedback.yourRating': 'Votre note',
    'feedback.yourComment': 'Votre commentaire',
    'feedback.reviewGivenOn': 'Avis donné le',
    'feedback.howRateService': 'Comment évaluez-vous ce service ?',
    'feedback.commentOptional': 'Commentaire (optionnel)',
    'feedback.shareYourExperience': 'Partagez votre expérience...',
    'feedback.characters': 'caractères',
    'feedback.sendReview': 'Envoyer mon avis',
    'feedback.sending': 'Envoi en cours...',
    'feedback.thankYou': 'Merci pour votre avis !',

    // Complaints Page
    'complaints.title': 'Mes Réclamations',
    'complaints.manageComplaints': 'Gérez vos réclamations et suivez leur traitement',
    'complaints.newComplaint': 'Nouvelle réclamation',
    'complaints.createComplaint': 'Créer une réclamation',
    'complaints.subject': 'Sujet',
    'complaints.description': 'Description',
    'complaints.noComplaints': 'Aucune réclamation',
    'complaints.notCreatedYet': 'Vous n\'avez pas encore créé de réclamation',
    'complaints.create': 'Créer une réclamation',
    'complaints.createdOn': 'Créée le',
    'complaints.complaintNumber': 'Réclamation',
    'complaints.teamResponse': 'Réponse de l\'équipe',
    'complaints.respondedOn': 'Répondu le',
    'complaints.submitted': 'Soumise',
    'complaints.inProgress': 'En cours',
    'complaints.processed': 'Traitée',
    'complaints.closed': 'Clôturée',
    'complaints.cancel': 'Annuler',
    'complaints.send': 'Envoyer',
    'complaints.sending': 'Envoi...',

    // Documents Page
    'documents.title': 'Mes Documents',
    'documents.accessImportantDocuments': 'Accédez à tous vos documents importants',
    'documents.noDocuments': 'Aucun document disponible',
    'documents.all': 'Tous',
    'documents.loading': 'Chargement...',
    'documents.addedOn': 'Ajouté le',
    'documents.size': 'Taille',
    'documents.view': 'Voir',
    'documents.download': 'Télécharger',

    // Invoices Page
    'invoices.title': 'Mes Factures',
    'invoices.noInvoices': 'Aucune facture disponible',
    'invoices.back': 'Retour',

    // Promotions Page
    'promotions.title': 'Promotions Véhicules',
    'promotions.discoverOffers': 'Découvrez nos offres exceptionnelles sur une sélection de véhicules neufs',
    'promotions.allBrands': 'Toutes les marques',
    'promotions.noPromotions': 'Aucune promotion disponible',
    'promotions.comeBackSoon': 'Revenez bientôt pour découvrir nos nouvelles offres !',
    'promotions.until': 'Jusqu\'au',
    'promotions.vehiclesAvailable': 'véhicule(s) disponible(s)',
    'promotions.outOfStock': 'Stock épuisé',
    'promotions.contactUs': 'Contactez-nous',
    'promotions.loadingPromotions': 'Chargement des promotions...',
    'promotions.conditions': 'Conditions',

    // Vehicle History Page
    'vehicleHistory.title': 'Historique de mes véhicules',
    'vehicleHistory.consultHistory': 'Consultez l\'historique complet de vos véhicules : interventions, rendez-vous et statistiques',
    'vehicleHistory.mileage': 'Kilométrage',
    'vehicleHistory.color': 'Couleur',
    'vehicleHistory.status': 'Statut',
    'vehicleHistory.viewHistory': 'Voir l\'historique',
    'vehicleHistory.whatContains': 'Que contient l\'historique',
    'vehicleHistory.allInterventions': 'Toutes les interventions effectuées sur votre véhicule',
    'vehicleHistory.completeHistory': 'L\'historique complet de vos rendez-vous',
    'vehicleHistory.costStatistics': 'Les statistiques de coûts de trajet',
    'vehicleHistory.exportData': 'La possibilité d\'exporter vos données',
    'vehicleHistory.noVehicles': 'Aucun véhicule enregistré',
    'vehicleHistory.addVehicleToConsult': 'Ajoutez un véhicule pour consulter son historique',
    'vehicleHistory.addVehicle': 'Ajouter un véhicule',
    'vehicleHistory.errorLoading': 'Erreur lors du chargement des véhicules',
    'vehicleHistory.notConnected': 'Utilisateur non connecté',
    'vehicleHistory.whatContainsTitle': 'Que contient l\'historique ?',
    'vehicleHistory.allInterventionsPerformed': 'Toutes les interventions effectuées sur votre véhicule',
    'vehicleHistory.completeAppointmentHistory': 'L\'historique complet de vos rendez-vous',
    'vehicleHistory.statisticsAndCosts': 'Les statistiques et coûts totaux',
    'vehicleHistory.exportPossibility': 'La possibilité d\'exporter vos données',
    'vehicleHistory.detailTitle': 'Historique du véhicule',
    'vehicleHistory.export': 'Exporter',
    'vehicleHistory.overview': 'Vue d\'ensemble',
    'vehicleHistory.interventions': 'Interventions',
    'vehicleHistory.appointments': 'Rendez-vous',
    'vehicleHistory.totalRDV': 'Total RDV',
    'vehicleHistory.totalCost': 'Coût total',
    'vehicleHistory.vehicleInfo': 'Informations du véhicule',
    'vehicleHistory.brandModel': 'Marque et modèle',
    'vehicleHistory.year': 'Année',
    'vehicleHistory.registration': 'Immatriculation',
    'vehicleHistory.purchaseDate': 'Date d\'achat',
    'vehicleHistory.lastIntervention': 'Dernière intervention',
    'vehicleHistory.nextRDV': 'Prochain RDV',
    'vehicleHistory.none': 'Aucune',
    'vehicleHistory.noneM': 'Aucun',
    'vehicleHistory.rdvStats': 'Statistiques des rendez-vous',
    'vehicleHistory.completed': 'Terminés',
    'vehicleHistory.cancelled': 'Annulés',
    'vehicleHistory.inProgress': 'En cours',
    'vehicleHistory.noInterventions': 'Aucune intervention enregistrée',
    'vehicleHistory.noAppointments': 'Aucun rendez-vous enregistré',
    'vehicleHistory.type': 'Type',
    'vehicleHistory.description': 'Description',
    'vehicleHistory.cost': 'Coût',
    'vehicleHistory.hour': 'Heure',
    'vehicleHistory.reason': 'Motif',
    'vehicleHistory.vehicleNotFound': 'Véhicule non trouvé',
    'vehicleHistory.exportError': 'Erreur lors de l\'export',

    // Assistance Page
    // Informations Page
    'informations.title': 'Informations et Documents',
    'informations.everythingYouNeed': 'Tout ce que vous devez savoir sur la garantie, l\'assurance et les documents requis',
    'informations.sections': 'Sections',
    'informations.articles': 'article',
    'informations.documents': 'document',
    'informations.downloadableDocuments': 'Documents Téléchargeables',
    'informations.noContent': 'Aucun contenu disponible pour cette section',
    'informations.downloads': 'téléchargement',
    'informations.downloadStarted': 'Téléchargement de {filename} démarré',
  },
  ar: {
    // Navigation
    'nav.dashboard': 'لوحة القيادة',
    'nav.catalog': 'الكتالوج',
    'nav.appointments': 'المواعيد',
    'nav.vehicles': 'المركبات',
    'nav.orders': 'الطلبات',
    'nav.complaints': 'الشكاوى',
    'nav.documents': 'المستندات',
    'nav.assistance': 'المساعدة',
    'nav.feedback': 'التقييمات',
    'nav.profile': 'الملف الشخصي',
    'nav.logout': 'تسجيل الخروج',
    'nav.clientDashboard': 'لوحة القيادة',
    'nav.clientVehicles': 'مركباتي',
    'nav.clientHistory': 'تاريخ المركبات',
    'nav.clientRepairOrders': 'أوامر الإصلاح',
    'nav.clientCatalog': 'الكتالوج',
    'nav.clientPromotions': 'العروض',
    'nav.clientAppointments': 'المواعيد',
    'nav.clientOrders': 'طلباتي',
    'nav.clientDocuments': 'مستنداتي',
    'nav.clientInformations': 'معلومات',
    'nav.clientChatbot': 'مساعد الصيانة',
    'nav.clientAssistance': 'المساعدة',
    'nav.clientFeedback': 'تقييماتي',
    'nav.clientComplaints': 'الشكاوى',
    'nav.clientProfile': 'ملفي الشخصي',
    'nav.clientSpace': 'فضاء الحريف',
    'PRINCIPAL': 'رئيسي',
    'SUIVI': 'متابعة',
    'AUTRES': 'أخرى',

    // Common
    'common.welcome': 'مرحبا',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.add': 'إضافة',
    'common.close': 'إغلاق',
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.confirm': 'تأكيد',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.submit': 'إرسال',
    'common.view': 'عرض',
    'common.download': 'تحميل',
    'common.upload': 'رفع',
    'common.select': 'اختر',
    'common.all': 'الكل',
    'common.none': 'لا شيء',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.details': 'التفاصيل',
    'common.unknown': 'غير محدد',
    'common.total': 'الإجمالي',
    'common.inProgress': 'قيد التنفيذ',
    'common.completed': 'مكتملة',
    'common.totalCost': 'التكلفة الإجمالية',
    'common.orders': 'طلباتي',
    'common.quickAccess': 'وصول سريع',
    'common.myVehicles': 'مركباتي',
    'common.editProfile': 'تعديل الملف الشخصي',
    'common.client': 'عميل',
    'common.email': 'البريد الإلكتروني',
    'common.phone': 'الهاتف',
    'common.clientId': 'معرف العميل',
    'common.addFirstVehicle': 'إضافة أول مركبة',
    'common.noVehicle': 'لا توجد مركبات مسجلة',
    'common.chassisNumber': 'رقم الهيكل',
    'common.vehiclesCount': 'المركبات',
    'common.nextAppointments': 'المواعيد القادمة',
    'common.send': 'إرسال',
    'common.writeMessage': 'اكتب رسالتك...',
    'common.available247': 'متاح 24/24',

    // Auth
    'auth.login': 'تسجيل الدخول',
    'auth.register': 'التسجيل',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.rememberMe': 'تذكرني',

    // Dashboard
    'dashboard.title': 'لوحة القيادة',
    'dashboard.stats': 'الإحصائيات',
    'dashboard.recentActivity': 'النشاط الأخير',
    'dashboard.welcomeBack': 'مرحبًا بعودتك',
    'dashboard.manageAppointments': 'إدارة مواعيد الورشة',
    'dashboard.managePersonalInfo': 'إدارة معلوماتك الشخصية',
    'dashboard.see': 'عرض',
    'dashboard.edit': 'تعديل',
    'dashboard.add': 'إضافة',
    'dashboard.hello': 'مرحبا',
    'dashboard.welcomeMessage': 'مرحبًا بك في فضاء العميل STA Chery Tunisia',
    'dashboard.takeAppointment': 'حجز موعد',
    'dashboard.myVehicles': 'مركباتي',
    'dashboard.upcomingAppointments': 'المواعيد القادمة',
    'dashboard.vehicles': 'المركبات',
    'dashboard.complaints': 'الشكاوى',
    'dashboard.completedAppointments': 'المواعيد المكتملة',
    'dashboard.thisMonth': 'هذا الشهر',
    'dashboard.myAppointments': 'مواعيدي',
    'dashboard.viewAll': 'عرض الكل',
    'dashboard.noUpcomingAppointments': 'لا توجد مواعيد قادمة',
    'dashboard.quickActions': 'إجراءات سريعة',
    'dashboard.bookAppointment': 'حجز موعد جديد',
    'dashboard.submitComplaint': 'تقديم شكوى',
    'dashboard.reportProblem': 'الإبلاغ عن مشكلة',
    'dashboard.noVehicles': 'لا توجد مركبات مسجلة',
    'dashboard.addVehicle': 'إضافة مركبة',
    'dashboard.serviceAppointment': 'موعد خدمة',
    'dashboard.vehicle': 'المركبة',
    'dashboard.agency': 'الوكالة',
    'dashboard.confirmed': 'مؤكد',
    'dashboard.planned': 'مخطط',
    'dashboard.inProgress': 'قيد التنفيذ',
    'dashboard.validated': 'تم التحقق',
    'dashboard.pending': 'قيد الانتظار',
    'dashboard.refused': 'مرفوض',
    'dashboard.undefined': 'غير محدد',
    'dashboard.unknownPlate': 'رقم لوحة غير معروف',

    // Catalog
    'catalog.title': 'كتالوج الخدمات',
    'catalog.packages': 'الباقات',
    'catalog.interventions': 'التدخلات',
    'catalog.price': 'السعر',
    'catalog.duration': 'المدة',
    'catalog.details': 'التفاصيل',
    'catalog.bookNow': 'احجز الآن',

    // Appointments
    'appointments.title': 'مواعيدي',
    'appointments.total': 'في المجموع',
    'appointments.manageAppointments': 'إدارة مواعيدك ومتابعة حالتها',
    'appointments.bookAppointment': 'حجز موعد',
    'appointments.vehicleValidationRequired': 'يجب انتظار التحقق من مركبتك من قبل وكيل الصيانة قبل حجز موعد.',
    'appointments.dayWithAppointment': 'يوم مع موعد',
    'appointments.today': 'اليوم',
    'appointments.allAppointments': 'جميع المواعيد',
    'appointments.all': 'الكل',
    'appointments.planned': 'مخططة',
    'appointments.inProgress': 'قيد التنفيذ',
    'appointments.completed': 'مكتملة',
    'appointments.noAppointmentsFound': 'لم يتم العثور على مواعيد',
    'appointments.bookNow': 'احجز الآن',
    'appointments.step': 'خطوة',
    'appointments.of': 'من',
    'appointments.selectVehicleAndService': 'اختر المركبة والخدمة',
    'appointments.agency': 'الوكالة',
    'appointments.selectAgency': 'اختر وكالة',
    'appointments.vehicle': 'المركبة',
    'appointments.selectVehicle': 'اختر مركبة',
    'appointments.serviceType': 'نوع الخدمة',
    'appointments.selectServiceType': 'اختر نوع الخدمة',
    'appointments.packagesAvailable': 'الباقات المتاحة',
    'appointments.packagesSelected': 'محدد',
    'appointments.estimatedTotalPrice': 'السعر الإجمالي المقدر',
    'appointments.packagesSelectedCount': 'باقة محددة',
    'appointments.selectDateAndTime': 'اختر التاريخ والوقت',
    'appointments.date': 'التاريخ',
    'appointments.timeSlot': 'الفترة الزمنية',
    'appointments.slotFull': 'الفترة ممتلئة',
    'appointments.reservations': 'حجوزات',
    'appointments.placesRemaining': 'مكان متبقي من',
    'appointments.full': 'ممتلئ',
    'appointments.available': 'متاح',
    'appointments.selectAvailableSlot': 'اختر فترة متاحة',
    'appointments.noSlotsAvailable': 'لا توجد فترات متاحة لهذا التاريخ',
    'appointments.noSlotsForDate': 'لا توجد فترات متاحة لهذا التاريخ. يرجى اختيار تاريخ آخر.',
    'appointments.additionalNotes': 'ملاحظات إضافية',
    'appointments.specialRequest': 'طلب خاص أو معلومات إضافية...',
    'appointments.characters': 'حرف',
    'appointments.verifyAndConfirm': 'التحقق والتأكيد',
    'appointments.within24h': 'تنبيه: أنت تحجز موعدًا في أقل من 24 ساعة. يرجى التأكد من توفرك.',
    'appointments.service': 'الخدمة',
    'appointments.selectedPackages': 'الباقات المحددة',
    'appointments.estimatedPrice': 'السعر المقدر',
    'appointments.time': 'الوقت',
    'appointments.remarks': 'ملاحظات',
    'appointments.back': 'رجوع',
    'appointments.next': 'التالي',
    'appointments.processing': 'جاري المعالجة...',
    'appointments.confirmAppointment': 'تأكيد الموعد',
    'appointments.detailsTitle': 'تفاصيل الموعد',
    'appointments.dateAndTime': 'التاريخ والوقت',
    'appointments.services': 'الخدمات',
    'appointments.servicesCount': 'خدمة',
    'appointments.serviceDetails': 'تفاصيل الخدمات',
    'appointments.noServiceSpecified': 'لم يتم تحديد خدمة',
    'appointments.notes': 'ملاحظات',
    'appointments.cancelAppointment': 'إلغاء الموعد',
    'appointments.cancelReason': 'سبب الإلغاء (اختياري)',
    'appointments.close': 'إغلاق',
    'appointments.cancelling': 'جاري الإلغاء...',
    'appointments.cancelButton': 'إلغاء الموعد',
    'appointments.errorSelectAll': 'يرجى تحديد جميع الحقول المطلوبة',
    'appointments.errorSelectDateTime': 'يرجى تحديد تاريخ ووقت',
    'appointments.new': 'موعد جديد',
    'appointments.status': 'الحالة',
    'appointments.cancel': 'إلغاء',

    // Vehicles
    'vehicles.title': 'مركباتي',
    'vehicles.add': 'إضافة مركبة',
    'vehicles.addVehicle': 'إضافة مركبة',
    'vehicles.addNewVehicle': 'إضافة مركبة جديدة',
    'vehicles.brand': 'العلامة التجارية',
    'vehicles.model': 'الطراز',
    'vehicles.year': 'السنة',
    'vehicles.vin': 'رقم الهيكل',
    'vehicles.plate': 'رقم اللوحة',
    'vehicles.registration': 'التسجيل',
    'vehicles.color': 'اللون',
    'vehicles.mileage': 'المسافة المقطوعة',
    'vehicles.validated': 'تم التحقق',
    'vehicles.registeredVehicles': 'مركبة (مركبات) مسجلة',
    'vehicles.confirmDelete': 'هل أنت متأكد من حذف هذه المركبة؟',
    'vehicles.deleteSuccess': 'تم حذف المركبة بنجاح',
    'vehicles.deleteError': 'خطأ في حذف المركبة',
    'vehicles.modify': 'تعديل',
    'vehicles.delete': 'حذف',
    'vehicles.vehicle': 'مركبة',
    'vehicles.detailsUnavailable': 'التفاصيل غير متوفرة',
    'vehicles.selectBrand': 'اختر علامة تجارية',
    'vehicles.selectModel': 'اختر طراز',
    'vehicles.selectVersion': 'اختر نسخة',
    'vehicles.selectColor': 'اختر لون',
    'vehicles.version': 'النسخة',
    'vehicles.chassisNumber': 'رقم الهيكل',
    'vehicles.plateType': 'نوع اللوحة',
    'vehicles.tunisFormat': 'صيغة تونس',
    'vehicles.ntFormat': 'صيغة ن.ت',
    'vehicles.maxPlateNumber': 'الرقم لا يمكن أن يتجاوز 260',
    'vehicles.preview': 'معاينة',
    'vehicles.loading': 'جاري التحميل...',
    'vehicles.photos': 'الصور',
    'vehicles.vehiclePhoto': 'صورة المركبة',
    'vehicles.carteGrisePhoto': 'صورة بطاقة الرمادية',
    'vehicles.imageFormat': 'الصيغة المقبولة: JPG، PNG (حد أقصى 5 ميجابايت)',
    'vehicles.removeImage': 'إزالة الصورة',
    'vehicles.vehicleAdded': 'تمت إضافة المركبة بنجاح',
    'vehicles.vehicleAddedSuccess': 'تم تسجيل مركبتك بنجاح. ستظهر في قائمتك بعد التحقق من قبل وكيل SAV.',
    'vehicles.viewMyVehicles': 'عرض مركباتي',
    'vehicles.vehicleInfo': 'معلومات المركبة',
    'vehicles.fillRequired': 'املأ الحقول المطلوبة',
    'vehicles.validationNotice': 'ملاحظة: بعد إضافة مركبتك، ستحتاج إلى انتظار التحقق من قبل وكيل SAV قبل أن تظهر في قائمتك.',
    'vehicles.optional': '(اختياري)',

    // Orders
    'orders.noOrders': 'لا توجد طلبات إصلاح',
    'orders.bookAppointment': 'حجز موعد',
    'orders.order': 'طلب',
    'orders.agency': 'الوكالة',
    'orders.interventions': 'التدخلات',
    'orders.cost': 'التكلفة',
    'orders.appointmentDate': 'تاريخ الموعد',
    'orders.estimatedDuration': 'المدة المقدرة',
    'orders.vehicle': 'المركبة',
    'orders.brandModel': 'العلامة/الطراز',
    'orders.plate': 'رقم اللوحة',
    'orders.color': 'اللون',
    'orders.year': 'السنة',
    'orders.agentAssigned': 'الوكيل المكلّف',
    'orders.attachments': 'المرفقات',
    'orders.download': 'تنزيل',
    'orders.undefined': 'غير محدد',
    'orders.loadingError': 'حدث خطأ أثناء تحميل الطلبات',
    'orders.detailsError': 'حدث خطأ أثناء تحميل التفاصيل',
    'orders.detailsTitle': 'تفاصيل الطلب',

    // Chatbot
    'chatbot.title': 'مساعد صيانة شيري',
    'chatbot.greeting': '👋 مرحبًا! أنا مساعد صيانة شيري تونس. كيف يمكنني مساعدتك؟',
    'chatbot.typing': 'المساعد يكتب الرد...',
    'chatbot.fallback': '⚠️ الخدمة غير متاحة مؤقتًا. اتصل بنا على +216 XX XXX XXX',

    // Assistance
    'assistance.title': 'مساعدة التشخيص',
    'assistance.subtitle': 'صِف مشكلتك وابحث عن الحلول',
    'assistance.findHelp': 'ابحث عن المساعدة التي تحتاجها',
    'assistance.searchInAssistance': 'البحث في المساعدة...',
    'assistance.search': 'بحث',
    'assistance.frequentQuestions': 'الأسئلة الشائعة',
    'assistance.findAnswers': 'ابحث عن إجابات للأسئلة الشائعة',
    'assistance.contactSupport': 'اتصل بالدعم',
    'assistance.talkDirectly': 'تحدث مباشرة مع فريقنا',
    'assistance.userGuide': 'دليل المستخدم',
    'assistance.learnToUse': 'تعلم كيفية استخدام المنصة',
    'assistance.liveChat': 'الدردشة المباشرة',
    'assistance.instantAssistance': 'مساعدة فورية',
    'assistance.access': 'الوصول',
    'assistance.enterProblem': 'يرجى إدخال وصف للمشكلة',
    'assistance.searchPlaceholder': 'مثال: صوت عند التشغيل، ضوء المحرك مضاء...',
    'assistance.searching': 'جاري البحث...',
    'assistance.viewSolution': 'عرض الحل',
    'assistance.problemDescription': 'وصف المشكلة',
    'assistance.recommendedSolution': 'الحل الموصى به',
    'assistance.problemPersists': '💡 إذا استمرت المشكلة، نوصي بحجز موعد مع أحد فنّينا.',
    'assistance.commonProblems': 'المشاكل الشائعة',
    'assistance.suggestion.engineLight': 'ضوء المحرك مضاء',
    'assistance.suggestion.brakeNoise': 'ضوضاء عند الفرملة',
    'assistance.suggestion.startIssue': 'مشكلة في التشغيل',
    'assistance.suggestion.acIssue': 'ضعف في التكييف',
    'assistance.suggestion.steeringVibration': 'اهتزاز في المقود',
    'assistance.suggestion.highConsumption': 'استهلاك مرتفع للوقود',

    // Notifications
    'notifications.title': 'الإشعارات',
    'notifications.markAllRead': 'تحديد الكل كمقروء',
    'notifications.empty': 'لا توجد إشعارات',
    'notifications.loading': 'جاري التحميل...',
    'notifications.justNow': 'الآن',
    'notifications.minutesAgo': 'منذ {count} دقيقة',
    'notifications.hoursAgo': 'منذ {count} ساعة',
    'notifications.yesterday': 'أمس',
    'notifications.daysAgo': 'منذ {count} يوم',
    'notifications.markedReadSuccess': 'تم تحديد جميع الإشعارات كمقروءة',

    // Language
    'language.french': 'Français',
    'language.arabic': 'العربية',
    'language.english': 'English',
    'language.select': 'اختر اللغة',
    'language.frShort': 'FR',
    'language.arShort': 'AR',
    'language.enShort': 'EN',

    // Profile Page
    'profile.title': 'الملف الشخصي',
    'profile.modifyInfo': 'تعديل المعلومات',
    'profile.updatePersonalInfo': 'قم بتحديث معلوماتك الشخصية',
    'profile.accountSecurity': 'أمان الحساب',
    'profile.changePasswordRegularly': 'قم بتغيير كلمة المرور بانتظام',
    'profile.currentPassword': 'كلمة المرور الحالية',
    'profile.newPassword': 'كلمة المرور الجديدة',
    'profile.confirmNewPassword': 'تأكيد كلمة المرور الجديدة',
    'profile.changePassword': 'تغيير كلمة المرور',
    'profile.saveChanges': 'حفظ التغييرات',
    'profile.firstName': 'الاسم الأول',
    'profile.lastName': 'اسم العائلة',
    'profile.passwordStrength': 'قوة كلمة المرور',
    'profile.weak': 'ضعيفة',
    'profile.medium': 'متوسطة',
    'profile.strong': 'قوية',
    'profile.saving': 'جاري الحفظ...',
    'profile.modifying': 'جاري التعديل...',
    'profile.notModifiable': 'غير قابل للتعديل',
    'profile.administrator': 'مدير',
    'profile.agent': 'وكيل الصيانة',
    'profile.direction': 'الإدارة',
    'profile.client': 'عميل',

    // Feedback Page
    'feedback.title': 'تقييماتك',
    'feedback.shareExperience': 'شارك تجربتك مع خدماتنا',
    'feedback.noCompletedAppointments': 'لا توجد مواعيد مكتملة',
    'feedback.leaveReviewAfterService': 'يمكنك ترك تقييم بعد أول خدمة لك',
    'feedback.appointment': 'موعد',
    'feedback.reviewGiven': 'تم إعطاء التقييم',
    'feedback.yourRating': 'تقييمك',
    'feedback.yourComment': 'تعليقك',
    'feedback.reviewGivenOn': 'تم التقييم في',
    'feedback.howRateService': 'كيف تقيم هذه الخدمة؟',
    'feedback.commentOptional': 'تعليق (اختياري)',
    'feedback.shareYourExperience': 'شارك تجربتك...',
    'feedback.characters': 'حرف',
    'feedback.sendReview': 'إرسال تقييمي',
    'feedback.sending': 'جاري الإرسال...',
    'feedback.thankYou': 'شكراً لتقييمك!',

    // Complaints Page
    'complaints.title': 'شكاواي',
    'complaints.manageComplaints': 'إدارة شكاواك ومتابعة معالجتها',
    'complaints.newComplaint': 'شكوى جديدة',
    'complaints.createComplaint': 'إنشاء شكوى',
    'complaints.subject': 'الموضوع',
    'complaints.description': 'الوصف',
    'complaints.noComplaints': 'لا توجد شكاوى',
    'complaints.notCreatedYet': 'لم تقم بإنشاء أي شكوى بعد',
    'complaints.create': 'إنشاء شكوى',
    'complaints.createdOn': 'تم الإنشاء في',
    'complaints.complaintNumber': 'شكوى',
    'complaints.teamResponse': 'رد الفريق',
    'complaints.respondedOn': 'تم الرد في',
    'complaints.submitted': 'مقدمة',
    'complaints.inProgress': 'قيد المعالجة',
    'complaints.processed': 'تمت المعالجة',
    'complaints.closed': 'مغلقة',
    'complaints.cancel': 'إلغاء',
    'complaints.send': 'إرسال',
    'complaints.sending': 'جاري الإرسال...',

    // Documents Page
    'documents.title': 'مستنداتي',
    'documents.accessImportantDocuments': 'الوصول إلى جميع مستنداتك المهمة',
    'documents.noDocuments': 'لا توجد مستندات متاحة',
    'documents.all': 'الكل',
    'documents.loading': 'جاري التحميل...',
    'documents.addedOn': 'تمت الإضافة في',
    'documents.size': 'الحجم',
    'documents.view': 'عرض',
    'documents.download': 'تنزيل',

    // Invoices Page
    'invoices.title': 'فواتيري',
    'invoices.noInvoices': 'لا توجد فواتير متاحة',
    'invoices.back': 'رجوع',

    // Promotions Page
    'promotions.title': 'عروض المركبات',
    'promotions.discoverOffers': 'اكتشف عروضنا الاستثنائية على مجموعة مختارة من المركبات الجديدة',
    'promotions.allBrands': 'جميع العلامات التجارية',
    'promotions.noPromotions': 'لا توجد عروض متاحة',
    'promotions.comeBackSoon': 'عد قريباً لاكتشاف عروضنا الجديدة!',
    'promotions.until': 'حتى',
    'promotions.vehiclesAvailable': 'مركبة متاحة',
    'promotions.outOfStock': 'نفذ المخزون',
    'promotions.contactUs': 'اتصل بنا',
    'promotions.loadingPromotions': 'جاري تحميل العروض...',
    'promotions.conditions': 'الشروط',

    // Catalog Page
    // Vehicle History Page
    'vehicleHistory.title': 'تاريخ مركباتي',
    'vehicleHistory.consultHistory': 'استشر التاريخ الكامل لمركباتك: التدخلات والمواعيد والإحصائيات',
    'vehicleHistory.mileage': 'المسافة المقطوعة',
    'vehicleHistory.color': 'اللون',
    'vehicleHistory.status': 'الحالة',
    'vehicleHistory.viewHistory': 'عرض التاريخ',
    'vehicleHistory.whatContains': 'ماذا يحتوي التاريخ',
    'vehicleHistory.allInterventions': 'جميع التدخلات المنفذة على مركبتك',
    'vehicleHistory.completeHistory': 'التاريخ الكامل لمواعيدك',
    'vehicleHistory.costStatistics': 'إحصائيات تكاليف الرحلة',
    'vehicleHistory.exportData': 'إمكانية تصدير بياناتك',
    'vehicleHistory.noVehicles': 'لا توجد مركبات مسجلة',
    'vehicleHistory.addVehicleToConsult': 'أضف مركبة لاستشارة تاريخها',
    'vehicleHistory.addVehicle': 'إضافة مركبة',
    'vehicleHistory.errorLoading': 'خطأ في تحميل المركبات',
    'vehicleHistory.notConnected': 'المستخدم غير متصل',
    'vehicleHistory.whatContainsTitle': 'ماذا يحتوي التاريخ؟',
    'vehicleHistory.allInterventionsPerformed': 'جميع التدخلات المنفذة على مركبتك',
    'vehicleHistory.completeAppointmentHistory': 'التاريخ الكامل لمواعيدك',
    'vehicleHistory.statisticsAndCosts': 'الإحصائيات والتكاليف الإجمالية',
    'vehicleHistory.exportPossibility': 'إمكانية تصدير بياناتك',

    // Appointments Page
    // Vehicles Page
    // Assistance Page
    // Informations Page
    'informations.title': 'المعلومات والمستندات',
    'informations.everythingYouNeed': 'كل ما تحتاج معرفته عن الضمان والتأمين والمستندات المطلوبة',
    'informations.sections': 'الأقسام',
    'informations.articles': 'مقال',
    'informations.documents': 'مستند',
    'informations.downloadableDocuments': 'المستندات القابلة للتنزيل',
    'informations.noContent': 'لا يوجد محتوى متاح لهذا القسم',
    'informations.downloads': 'تنزيل',
    'informations.downloadStarted': 'بدأ تنزيل {filename}',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.catalog': 'Catalog',
    'nav.appointments': 'Appointments',
    'nav.vehicles': 'Vehicles',
    'nav.orders': 'Orders',
    'nav.complaints': 'Complaints',
    'nav.documents': 'Documents',
    'nav.assistance': 'Assistance',
    'nav.feedback': 'Reviews',
    'nav.profile': 'Profile',
    'nav.logout': 'Logout',
    'nav.clientDashboard': 'Dashboard',
    'nav.clientVehicles': 'My Vehicles',
    'nav.clientHistory': 'Vehicle History',
    'nav.clientRepairOrders': 'Repair Orders',
    'nav.clientCatalog': 'Catalog',
    'nav.clientPromotions': 'Promotions',
    'nav.clientOrders': 'My Orders',
    'nav.clientAppointments': 'Appointments',
    'nav.clientDocuments': 'My Documents',
    'nav.clientInformations': 'Informations',
    'nav.clientChatbot': 'Service Assistant',
    'nav.clientAssistance': 'Assistance',
    'nav.clientFeedback': 'My Reviews',
    'nav.clientComplaints': 'Complaints',
    'nav.clientProfile': 'My Profile',
    'nav.clientSpace': 'Client Space',
    'PRINCIPAL': 'MAIN',
    'SUIVI': 'TRACKING',
    'AUTRES': 'OTHERS',

    // Common
    'common.welcome': 'Welcome',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.close': 'Close',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.view': 'View',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.select': 'Select',
    'common.all': 'All',
    'common.none': 'None',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.details': 'Details',
    'common.unknown': 'Undefined',
    'common.total': 'Total',
    'common.inProgress': 'In Progress',
    'common.completed': 'Completed',
    'common.totalCost': 'Total Cost',
    'common.repairOrders': 'My Repair Orders',
    'common.quickAccess': 'Quick Access',
    'common.myVehicles': 'My Vehicles',
    'common.editProfile': 'Edit Profile',
    'common.client': 'CLIENT',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.clientId': 'Client ID',
    'common.addFirstVehicle': 'Add my first vehicle',
    'common.noVehicle': 'No registered vehicle',
    'common.chassisNumber': 'Chassis No.',
    'common.vehiclesCount': 'Vehicles',
    'common.nextAppointments': 'Upcoming Appointments',
    'common.send': 'Send',
    'common.writeMessage': 'Write your message...',
    'common.available247': 'Available 24/7',

    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.rememberMe': 'Remember me',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.stats': 'Statistics',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.welcomeBack': 'Welcome back',
    'dashboard.manageAppointments': 'Manage your workshop appointments',
    'dashboard.managePersonalInfo': 'Manage your personal information',
    'dashboard.see': 'View',
    'dashboard.edit': 'Edit',
    'dashboard.add': 'Add',
    'dashboard.hello': 'Hello',
    'dashboard.welcomeMessage': 'Welcome to your STA Chery Tunisia client space',
    'dashboard.takeAppointment': 'Book Appointment',
    'dashboard.myVehicles': 'My Vehicles',
    'dashboard.upcomingAppointments': 'Upcoming Appointments',
    'dashboard.vehicles': 'Vehicles',
    'dashboard.complaints': 'Complaints',
    'dashboard.completedAppointments': 'Completed Appointments',
    'dashboard.thisMonth': 'this month',
    'dashboard.myAppointments': 'My Appointments',
    'dashboard.viewAll': 'View All',
    'dashboard.noUpcomingAppointments': 'No upcoming appointments',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.bookAppointment': 'Book a new appointment',
    'dashboard.submitComplaint': 'Submit Complaint',
    'dashboard.reportProblem': 'Report a problem',
    'dashboard.noVehicles': 'No registered vehicles',
    'dashboard.addVehicle': 'Add Vehicle',
    'dashboard.serviceAppointment': 'Service Appointment',
    'dashboard.vehicle': 'Vehicle',
    'dashboard.agency': 'Agency',
    'dashboard.confirmed': 'Confirmed',
    'dashboard.planned': 'Planned',
    'dashboard.inProgress': 'In Progress',
    'dashboard.validated': 'Validated',
    'dashboard.pending': 'Pending',
    'dashboard.refused': 'Refused',
    'dashboard.undefined': 'Undefined',
    'dashboard.unknownPlate': 'Unknown plate',

    // Catalog
    'catalog.title': 'Service Catalog',
    'catalog.packages': 'Packages',
    'catalog.interventions': 'Interventions',
    'catalog.price': 'Price',
    'catalog.duration': 'Duration',
    'catalog.details': 'Details',
    'catalog.bookNow': 'Book Now',

    // Appointments
    'appointments.title': 'My Appointments',
    'appointments.total': 'total',
    'appointments.manageAppointments': 'Manage your appointments and track their status',
    'appointments.bookAppointment': 'Book Appointment',
    'appointments.vehicleValidationRequired': 'You must wait for your vehicle to be validated by a service agent before booking an appointment.',
    'appointments.dayWithAppointment': 'Day with appointment',
    'appointments.today': 'Today',
    'appointments.allAppointments': 'All Appointments',
    'appointments.all': 'All',
    'appointments.planned': 'Scheduled',
    'appointments.inProgress': 'In Progress',
    'appointments.completed': 'Completed',
    'appointments.noAppointmentsFound': 'No appointments found',
    'appointments.bookNow': 'Book Now',
    'appointments.step': 'Step',
    'appointments.of': 'of',
    'appointments.selectVehicleAndService': 'Select Vehicle and Service',
    'appointments.agency': 'Agency',
    'appointments.selectAgency': 'Select an agency',
    'appointments.vehicle': 'Vehicle',
    'appointments.selectVehicle': 'Select a vehicle',
    'appointments.serviceType': 'Service Type',
    'appointments.selectServiceType': 'Select a service type',
    'appointments.packagesAvailable': 'Available Packages',
    'appointments.packagesSelected': 'selected',
    'appointments.estimatedTotalPrice': 'Estimated Total Price',
    'appointments.packagesSelectedCount': 'package(s) selected',
    'appointments.selectDateAndTime': 'Select Date and Time',
    'appointments.date': 'Date',
    'appointments.timeSlot': 'Time Slot',
    'appointments.slotFull': 'Slot full',
    'appointments.reservations': 'reservations',
    'appointments.placesRemaining': 'place(s) remaining out of',
    'appointments.full': 'Full',
    'appointments.available': 'available',
    'appointments.selectAvailableSlot': 'Select an available slot',
    'appointments.noSlotsAvailable': 'No slots available for this date',
    'appointments.noSlotsForDate': 'No slots available for this date. Please select another date.',
    'appointments.additionalNotes': 'Additional Notes',
    'appointments.specialRequest': 'Special request or additional information...',
    'appointments.characters': 'characters',
    'appointments.verifyAndConfirm': 'Verify and Confirm',
    'appointments.within24h': 'Warning: You are booking an appointment in less than 24 hours. Please ensure your availability.',
    'appointments.service': 'Service',
    'appointments.selectedPackages': 'Selected Packages',
    'appointments.estimatedPrice': 'Estimated Price',
    'appointments.time': 'Time',
    'appointments.remarks': 'Remarks',
    'appointments.back': 'Back',
    'appointments.next': 'Next',
    'appointments.processing': 'Processing...',
    'appointments.confirmAppointment': 'Confirm Appointment',
    'appointments.detailsTitle': 'Appointment Details',
    'appointments.dateAndTime': 'Date and Time',
    'appointments.services': 'Services',
    'appointments.servicesCount': 'service(s)',
    'appointments.serviceDetails': 'Service Details',
    'appointments.noServiceSpecified': 'No service specified',
    'appointments.notes': 'Notes',
    'appointments.cancelAppointment': 'Cancel Appointment',
    'appointments.cancelReason': 'Cancellation reason (optional)',
    'appointments.close': 'Close',
    'appointments.cancelling': 'Cancelling...',
    'appointments.cancelButton': 'Cancel Appointment',
    'appointments.errorSelectAll': 'Please select all required fields',
    'appointments.errorSelectDateTime': 'Please select a date and time',
    'appointments.new': 'New Appointment',
    'appointments.status': 'Status',
    'appointments.cancel': 'Cancel',

    // Vehicles
    'vehicles.title': 'My Vehicles',
    'vehicles.add': 'Add Vehicle',
    'vehicles.addVehicle': 'Add Vehicle',
    'vehicles.addNewVehicle': 'Add New Vehicle',
    'vehicles.brand': 'Brand',
    'vehicles.model': 'Model',
    'vehicles.year': 'Year',
    'vehicles.vin': 'Chassis Number',
    'vehicles.plate': 'License Plate',
    'vehicles.registration': 'Registration',
    'vehicles.color': 'Color',
    'vehicles.mileage': 'Mileage',
    'vehicles.validated': 'Validated',
    'vehicles.registeredVehicles': 'registered vehicle(s)',
    'vehicles.confirmDelete': 'Are you sure you want to delete this vehicle?',
    'vehicles.deleteSuccess': 'Vehicle deleted successfully',
    'vehicles.deleteError': 'Error deleting vehicle',
    'vehicles.modify': 'Modify',
    'vehicles.delete': 'Delete',
    'vehicles.vehicle': 'Vehicle',
    'vehicles.detailsUnavailable': 'Details unavailable',
    'vehicles.selectBrand': 'Select a brand',
    'vehicles.selectModel': 'Select a model',
    'vehicles.selectVersion': 'Select a version',
    'vehicles.selectColor': 'Select a color',
    'vehicles.version': 'Version',
    'vehicles.chassisNumber': 'Chassis Number',
    'vehicles.plateType': 'Plate Type',
    'vehicles.tunisFormat': 'Tunis Format',
    'vehicles.ntFormat': 'N.T Format',
    'vehicles.maxPlateNumber': 'Number cannot exceed 260',
    'vehicles.preview': 'Preview',
    'vehicles.loading': 'Loading...',
    'vehicles.photos': 'Photos',
    'vehicles.vehiclePhoto': 'Vehicle Photo',
    'vehicles.carteGrisePhoto': 'Registration Card Photo',
    'vehicles.imageFormat': 'Accepted format: JPG, PNG (max 5MB)',
    'vehicles.removeImage': 'Remove image',
    'vehicles.vehicleAdded': 'Vehicle Added Successfully',
    'vehicles.vehicleAddedSuccess': 'Your vehicle has been registered successfully. It will appear in your list after validation by a SAV agent.',
    'vehicles.viewMyVehicles': 'View My Vehicles',
    'vehicles.vehicleInfo': 'Vehicle Information',
    'vehicles.fillRequired': 'Fill in the required fields',
    'vehicles.validationNotice': 'Note: After adding your vehicle, you will need to wait for validation from a SAV agent before it appears in your list.',
    'vehicles.optional': '(Optional)',

    // Orders
    'orders.noOrders': 'No repair orders',
    'orders.bookAppointment': 'Book an appointment',
    'orders.order': 'Order',
    'orders.agency': 'Agency',
    'orders.interventions': 'Interventions',
    'orders.cost': 'Cost',
    'orders.appointmentDate': 'Appointment Date',
    'orders.estimatedDuration': 'Estimated Duration',
    'orders.vehicle': 'Vehicle',
    'orders.brandModel': 'Brand/Model',
    'orders.plate': 'License Plate',
    'orders.color': 'Color',
    'orders.year': 'Year',
    'orders.agentAssigned': 'Assigned Agent',
    'orders.attachments': 'Attachments',
    'orders.download': 'Download',
    'orders.undefined': 'Undefined',
    'orders.loadingError': 'Error loading orders',
    'orders.detailsError': 'Error loading details',
    'orders.detailsTitle': 'Order Details',

    // Chatbot
    'chatbot.title': 'Chery Service Assistant',
    'chatbot.greeting': '👋 Hello! I am the Chery Tunisia service assistant. How can I help you?',
    'chatbot.typing': 'Assistant is typing...',
    'chatbot.fallback': '⚠️ Service temporarily unavailable. Call us at +216 XX XXX XXX',

    // Assistance
    'assistance.title': 'Diagnostic Assistance',
    'assistance.subtitle': 'Describe your problem and find solutions',
    'assistance.findHelp': 'Find the help you need',
    'assistance.searchInAssistance': 'Search in assistance...',
    'assistance.search': 'Search',
    'assistance.frequentQuestions': 'Frequent Questions',
    'assistance.findAnswers': 'Find answers to common questions',
    'assistance.contactSupport': 'Contact Support',
    'assistance.talkDirectly': 'Talk directly with our team',
    'assistance.userGuide': 'User Guide',
    'assistance.learnToUse': 'Learn how to use the platform',
    'assistance.liveChat': 'Live Chat',
    'assistance.instantAssistance': 'Instant assistance',
    'assistance.access': 'Access',
    'assistance.enterProblem': 'Please enter a problem description',
    'assistance.searchPlaceholder': 'Ex: Noise at startup, engine light on...',
    'assistance.searching': 'Searching...',
    'assistance.viewSolution': 'View Solution',
    'assistance.problemDescription': 'Problem Description',
    'assistance.recommendedSolution': 'Recommended Solution',
    'assistance.problemPersists': '💡 If the problem persists, we recommend booking an appointment with one of our technicians.',
    'assistance.commonProblems': 'Common Problems',
    'assistance.suggestion.engineLight': 'Engine light on',
    'assistance.suggestion.brakeNoise': 'Brake noise',
    'assistance.suggestion.startIssue': 'Starting problem',
    'assistance.suggestion.acIssue': 'Ineffective air conditioning',
    'assistance.suggestion.steeringVibration': 'Steering wheel vibrations',
    'assistance.suggestion.highConsumption': 'Excessive consumption',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.empty': 'No notifications',
    'notifications.loading': 'Loading...',
    'notifications.justNow': 'Just now',
    'notifications.minutesAgo': '{count} min ago',
    'notifications.hoursAgo': '{count}h ago',
    'notifications.yesterday': 'Yesterday',
    'notifications.daysAgo': '{count}d ago',
    'notifications.markedReadSuccess': 'All notifications marked as read',

    // Language
    'language.french': 'Français',
    'language.arabic': 'العربية',
    'language.english': 'English',
    'language.select': 'Select Language',
    'language.frShort': 'FR',
    'language.arShort': 'AR',
    'language.enShort': 'EN',

    // Profile Page
    'profile.title': 'Profile',
    'profile.modifyInfo': 'Modify Information',
    'profile.updatePersonalInfo': 'Update your personal information',
    'profile.accountSecurity': 'Account Security',
    'profile.changePasswordRegularly': 'Change your password regularly',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmNewPassword': 'Confirm New Password',
    'profile.changePassword': 'Change Password',
    'profile.saveChanges': 'Save Changes',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.passwordStrength': 'Password Strength',
    'profile.weak': 'Weak',
    'profile.medium': 'Medium',
    'profile.strong': 'Strong',
    'profile.saving': 'Saving...',
    'profile.modifying': 'Modifying...',
    'profile.notModifiable': 'Not Modifiable',
    'profile.administrator': 'Administrator',
    'profile.agent': 'Service Agent',
    'profile.direction': 'Management',
    'profile.client': 'Client',

    // Feedback Page
    'feedback.title': 'Your Reviews',
    'feedback.shareExperience': 'Share your experience with our services',
    'feedback.noCompletedAppointments': 'No completed appointments',
    'feedback.leaveReviewAfterService': 'You can leave a review after your first service',
    'feedback.appointment': 'Appointment',
    'feedback.reviewGiven': 'Review Given',
    'feedback.yourRating': 'Your Rating',
    'feedback.yourComment': 'Your Comment',
    'feedback.reviewGivenOn': 'Review given on',
    'feedback.howRateService': 'How do you rate this service?',
    'feedback.commentOptional': 'Comment (optional)',
    'feedback.shareYourExperience': 'Share your experience...',
    'feedback.characters': 'characters',
    'feedback.sendReview': 'Send My Review',
    'feedback.sending': 'Sending...',
    'feedback.thankYou': 'Thank you for your review!',

    // Complaints Page
    'complaints.title': 'My Complaints',
    'complaints.manageComplaints': 'Manage your complaints and track their processing',
    'complaints.newComplaint': 'New Complaint',
    'complaints.createComplaint': 'Create a Complaint',
    'complaints.subject': 'Subject',
    'complaints.description': 'Description',
    'complaints.noComplaints': 'No Complaints',
    'complaints.notCreatedYet': 'You haven\'t created any complaints yet',
    'complaints.create': 'Create a Complaint',
    'complaints.createdOn': 'Created on',
    'complaints.complaintNumber': 'Complaint',
    'complaints.teamResponse': 'Team Response',
    'complaints.respondedOn': 'Responded on',
    'complaints.submitted': 'Submitted',
    'complaints.inProgress': 'In Progress',
    'complaints.processed': 'Processed',
    'complaints.closed': 'Closed',
    'complaints.cancel': 'Cancel',
    'complaints.send': 'Send',
    'complaints.sending': 'Sending...',

    // Documents Page
    'documents.title': 'My Documents',
    'documents.accessImportantDocuments': 'Access all your important documents',
    'documents.noDocuments': 'No documents available',
    'documents.all': 'All',
    'documents.loading': 'Loading...',
    'documents.addedOn': 'Added on',
    'documents.size': 'Size',
    'documents.view': 'View',
    'documents.download': 'Download',

    // Invoices Page
    'invoices.title': 'My Invoices',
    'invoices.noInvoices': 'No invoices available',
    'invoices.back': 'Back',

    // Promotions Page
    'promotions.title': 'Vehicle Promotions',
    'promotions.discoverOffers': 'Discover our exceptional offers on a selection of new vehicles',
    'promotions.allBrands': 'All Brands',
    'promotions.noPromotions': 'No promotions available',
    'promotions.comeBackSoon': 'Come back soon to discover our new offers!',
    'promotions.until': 'Until',
    'promotions.vehiclesAvailable': 'vehicle(s) available',
    'promotions.outOfStock': 'Out of Stock',
    'promotions.contactUs': 'Contact Us',
    'promotions.loadingPromotions': 'Loading promotions...',
    'promotions.conditions': 'Conditions',

    // Catalog Page
    // Vehicle History Page
    'vehicleHistory.title': 'My Vehicle History',
    'vehicleHistory.consultHistory': 'Consult the complete history of your vehicles: interventions, appointments and statistics',
    'vehicleHistory.mileage': 'Mileage',
    'vehicleHistory.color': 'Color',
    'vehicleHistory.status': 'Status',
    'vehicleHistory.viewHistory': 'View History',
    'vehicleHistory.whatContains': 'What the history contains',
    'vehicleHistory.allInterventions': 'All interventions performed on your vehicle',
    'vehicleHistory.completeHistory': 'The complete history of your appointments',
    'vehicleHistory.costStatistics': 'Trip cost statistics',
    'vehicleHistory.exportData': 'The ability to export your data',
    'vehicleHistory.noVehicles': 'No registered vehicles',
    'vehicleHistory.addVehicleToConsult': 'Add a vehicle to consult its history',
    'vehicleHistory.addVehicle': 'Add a vehicle',
    'vehicleHistory.errorLoading': 'Error loading vehicles',
    'vehicleHistory.notConnected': 'User not connected',
    'vehicleHistory.whatContainsTitle': 'What does the history contain?',
    'vehicleHistory.allInterventionsPerformed': 'All interventions performed on your vehicle',
    'vehicleHistory.completeAppointmentHistory': 'The complete history of your appointments',
    'vehicleHistory.statisticsAndCosts': 'Statistics and total costs',
    'vehicleHistory.exportPossibility': 'The ability to export your data',

    // Appointments Page
    // Vehicles Page
    // Assistance Page
    // Informations Page
    'informations.title': 'Information and Documents',
    'informations.everythingYouNeed': 'Everything you need to know about warranty, insurance and required documents',
    'informations.sections': 'Sections',
    'informations.articles': 'article',
    'informations.documents': 'document',
    'informations.downloadableDocuments': 'Downloadable Documents',
    'informations.noContent': 'No content available for this section',
    'informations.downloads': 'download',
    'informations.downloadStarted': 'Download of {filename} started',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('fr');

  const applyDocumentLanguage = (lang: Language) => {
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  };

  const resolvePreferredLanguage = (): Language => {
    const savedLang = localStorage.getItem('language');
    if (savedLang === 'ar' || savedLang === 'fr' || savedLang === 'en') {
      return savedLang;
    }

    const browserLanguage = typeof navigator !== 'undefined' ? navigator.language.toLowerCase() : '';
    if (browserLanguage.startsWith('ar')) return 'ar';
    if (browserLanguage.startsWith('en')) return 'en';
    return 'fr';
  };

  useEffect(() => {
    const preferredLanguage = resolvePreferredLanguage();
    setLanguageState(preferredLanguage);
    localStorage.setItem('language', preferredLanguage);
  }, []);

  useEffect(() => {
    applyDocumentLanguage(language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    applyDocumentLanguage(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.fr[key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
